### ISSUE TITLE
No matching Function SHT31::begin()

### ISSUE THREAD

**Issue by Supplespence** [Seeed-Studio/Grove_SHT31_Temp_Humi_Sensor#4]
Example code no longer works

**Comment by lnatalis** [comment]
Hi, 

Yes, I confirm, if we launch the example code, we have an error at line 11

"No matching function for call to 'SHT31::begin()'

As a result, I cannot yet use the groove SHT31 sensor, do you have an update about this issue, or a workaround ? 

Many thanks!

**Comment by lakshanthad** [comment]
Hello,

It compiless fine for me. Could you please try again, please?

**Comment by Lesords** [comment]
Hello,
I'm sorry it took me so long to reply to you. 
Does this problem still exist? If so, can you provide a reproducible environment?

**Comment by Lesords** [comment]
I can compile it fine in the following environment.
arduino IDE version: 2.3.2
Board: XIAO ESP32C3

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
