### ISSUE TITLE
Example sketch not visible in Arduino IDE

### ISSUE THREAD

**Issue by wollewald** [Seeed-Studio/Grove_SHT31_Temp_Humi_Sensor#5]
Your library, or, to be more exact the xample sketch, does not appear in the Arduino IDE. 

You simply need to transfer example.ino into a subfolder called example. 

That means: 
Current: examples/example.ino

Correct: examples/example/example.ino 

Apart from that the library works fine!

**Comment by lakshanthad** [comment]
Hello,

`example.ino` is already inside the subfolder `example`

https://github.com/Seeed-Studio/Grove_SHT31_Temp_Humi_Sensor/blob/master/examples/example/example.ino

And I can see this example in Arduino IDE. Could you please double-check?

Thank you.

Best Regards,
Lakshantha

**Comment by wollewald** [comment]
It's OK!

**Comment by wollewald** [comment]
But I have another one for you:

````
uint16_t SHT31::readStatus(void) {
}
````

This is function is empty and has no return  but should have uint16_t.

I won't open another issue for this.

**Comment by lakshanthad** [comment]
Hello,

The "readStatus" function is unused at the moment. So I have deleted it.
https://github.com/Seeed-Studio/Grove_SHT31_Temp_Humi_Sensor/commit/7c96f264306bcbc721eafeb847d0d00af9a1c31d
